name: Example

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
      - run: ruff check --fix
      - run: ruff format
      - name: Run basedpyright
        run: uv run basedpyright # no additional arguments required. it automatically detects if it's running in a github action
